version: '3'

services:
    model-service-go:
      image: golang:1.12.1
      working_dir: /go/src/model-service
      volumes:
        - './:.'
      environment:
        MONGO_HOST: model-service-mongo
        MONGO_USERNAME: root
        MONGO_PASSWORD: root

    model-service-mongo:
      image: mongo:4.0.8
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
