// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response int32

const (
	Response_SUCCESS        Response = 0
	Response_INTERNAL_ERROR Response = 1
	Response_EMAIL_TAKEN    Response = 2
	Response_NOT_FOUND      Response = 3
)

var Response_name = map[int32]string{
	0: "SUCCESS",
	1: "INTERNAL_ERROR",
	2: "EMAIL_TAKEN",
	3: "NOT_FOUND",
}

var Response_value = map[string]int32{
	"SUCCESS":        0,
	"INTERNAL_ERROR": 1,
	"EMAIL_TAKEN":    2,
	"NOT_FOUND":      3,
}

func (x Response) String() string {
	return proto.EnumName(Response_name, int32(x))
}

func (Response) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterReply struct {
	Response             Response `protobuf:"varint,1,opt,name=response,proto3,enum=model.Response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetResponse() Response {
	if m != nil {
		return m.Response
	}
	return Response_SUCCESS
}

type ActivateRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateRequest) Reset()         { *m = ActivateRequest{} }
func (m *ActivateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateRequest) ProtoMessage()    {}
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *ActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateRequest.Unmarshal(m, b)
}
func (m *ActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateRequest.Marshal(b, m, deterministic)
}
func (m *ActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateRequest.Merge(m, src)
}
func (m *ActivateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateRequest.Size(m)
}
func (m *ActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateRequest proto.InternalMessageInfo

func (m *ActivateRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ActivateReply struct {
	Response             Response `protobuf:"varint,1,opt,name=response,proto3,enum=model.Response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateReply) Reset()         { *m = ActivateReply{} }
func (m *ActivateReply) String() string { return proto.CompactTextString(m) }
func (*ActivateReply) ProtoMessage()    {}
func (*ActivateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *ActivateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateReply.Unmarshal(m, b)
}
func (m *ActivateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateReply.Marshal(b, m, deterministic)
}
func (m *ActivateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateReply.Merge(m, src)
}
func (m *ActivateReply) XXX_Size() int {
	return xxx_messageInfo_ActivateReply.Size(m)
}
func (m *ActivateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateReply proto.InternalMessageInfo

func (m *ActivateReply) GetResponse() Response {
	if m != nil {
		return m.Response
	}
	return Response_SUCCESS
}

func init() {
	proto.RegisterEnum("model.Response", Response_name, Response_value)
	proto.RegisterType((*RegisterRequest)(nil), "model.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "model.RegisterReply")
	proto.RegisterType((*ActivateRequest)(nil), "model.ActivateRequest")
	proto.RegisterType((*ActivateReply)(nil), "model.ActivateReply")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x2d, 0x18, 0x94, 0x0e, 0xe1, 0x23, 0x93, 0xc6, 0x34, 0x3d, 0x29, 0x27, 0xa3, 0x49, 0x0f,
	0xf5, 0x66, 0xbc, 0x10, 0xc4, 0xa4, 0x69, 0x0b, 0xc9, 0x40, 0xcf, 0x04, 0x65, 0x63, 0x48, 0xa8,
	0x20, 0x8b, 0x9a, 0x9e, 0xfc, 0xeb, 0x86, 0x45, 0xb6, 0xa9, 0x9e, 0x3c, 0xbe, 0xb7, 0xf3, 0xde,
	0xdb, 0x37, 0x03, 0xc6, 0xae, 0xca, 0x59, 0x39, 0xaf, 0x9b, 0xaa, 0xad, 0x50, 0x13, 0xc0, 0xf5,
	0xc1, 0x26, 0xf6, 0x52, 0xf0, 0x96, 0x35, 0xc4, 0xde, 0xde, 0x19, 0x6f, 0x71, 0x02, 0x1a, 0xdb,
	0x65, 0x45, 0x39, 0x55, 0x2e, 0x94, 0xab, 0x31, 0xf5, 0x00, 0x67, 0xa0, 0xd7, 0x19, 0xe7, 0x9f,
	0x55, 0x93, 0x4f, 0x55, 0xf1, 0x20, 0xb1, 0x7b, 0x0f, 0xe6, 0xc1, 0xa4, 0x2e, 0xf7, 0x78, 0x03,
	0x7a, 0xc3, 0x78, 0x5d, 0xbd, 0x72, 0x26, 0x5c, 0xac, 0x85, 0x3d, 0xef, 0xc3, 0xe9, 0x87, 0x26,
	0x39, 0xe0, 0x5e, 0x82, 0xed, 0x3d, 0xb7, 0xc5, 0x47, 0xd6, 0xb2, 0xe1, 0x0b, 0x16, 0xa8, 0x45,
	0x2e, 0x94, 0x26, 0xa9, 0x85, 0x08, 0x38, 0x8c, 0xfc, 0x37, 0xe0, 0x7a, 0x05, 0xfa, 0xc0, 0xa2,
	0x01, 0x67, 0xf1, 0xd6, 0xf7, 0x83, 0x38, 0x76, 0x46, 0x88, 0x60, 0x2d, 0xc3, 0x24, 0xa0, 0xd0,
	0x5b, 0xa7, 0x01, 0x51, 0x44, 0x8e, 0x82, 0x36, 0x18, 0xc1, 0xc6, 0x5b, 0xae, 0xd3, 0xc4, 0x5b,
	0x05, 0xa1, 0xa3, 0xa2, 0x09, 0xe3, 0x30, 0x4a, 0xd2, 0xc7, 0x68, 0x1b, 0x3e, 0x38, 0x27, 0x8b,
	0x2f, 0xd0, 0x36, 0x5d, 0x10, 0xde, 0x75, 0xae, 0x7d, 0x69, 0x3c, 0x97, 0xe1, 0x47, 0xab, 0x9c,
	0x4d, 0xfe, 0xf0, 0x75, 0xb9, 0x77, 0x47, 0x9d, 0x76, 0xe8, 0x23, 0xb5, 0xbf, 0x76, 0x20, 0xb5,
	0x47, 0xc5, 0xdd, 0xd1, 0xd3, 0xa9, 0xb8, 0xdf, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f,
	0xbe, 0x0c, 0xd6, 0xce, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModelClient is the client API for Model service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateReply, error)
}

type modelClient struct {
	cc *grpc.ClientConn
}

func NewModelClient(cc *grpc.ClientConn) ModelClient {
	return &modelClient{cc}
}

func (c *modelClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/model.Model/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateReply, error) {
	out := new(ActivateReply)
	err := c.cc.Invoke(ctx, "/model.Model/Activate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServer is the server API for Model service.
type ModelServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	Activate(context.Context, *ActivateRequest) (*ActivateReply, error)
}

func RegisterModelServer(s *grpc.Server, srv ModelServer) {
	s.RegisterService(&_Model_serviceDesc, srv)
}

func _Model_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Model/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Model/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Model_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Model",
	HandlerType: (*ModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Model_Register_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _Model_Activate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}
